version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean test package
  post_build:
    commands:
      - echo Build completed on `date`
##      - cd target/surefire-reports; zip -r ../reports.zip *.xml
artifacts:
  files:
    - target/EmployeeApplication_*.war
    - target/surefire-reports/*.xml
